### ISSUE TITLE
download fails

### ISSUE THREAD

**Issue by NARKOZ** [akitaonrails/manga-downloadr#2]
```
Massive parallel download of all page images 
~~/lib/ruby/2.1.0/fileutils.rb:250:in `mkdir': Permission denied @ dir_s_mkdir - /vagrant (Errno::EACCES)
        from ~~/lib/ruby/2.1.0/fileutils.rb:250:in `fu_mkdir'
        from ~~/lib/ruby/2.1.0/fileutils.rb:224:in `block (2 levels) in mkdir_p'
        from ~~/lib/ruby/2.1.0/fileutils.rb:222:in `reverse_each'
        from ~~/lib/ruby/2.1.0/fileutils.rb:222:in `block in mkdir_p'
        from ~~/lib/ruby/2.1.0/fileutils.rb:208:in `each'
        from ~~/lib/ruby/2.1.0/fileutils.rb:208:in `mkdir_p'
        from ~~/gems/manga-downloadr-1.0.1/lib/manga-downloadr.rb:107:in `block (3 levels) in fetch_images!'
        from ~~/gems/typhoeus-0.6.9/lib/typhoeus/request/callbacks.rb:129:in `call'
        from ~~/gems/typhoeus-0.6.9/lib/typhoeus/request/callbacks.rb:129:in `block in execute_callbacks'
        from ~~/gems/typhoeus-0.6.9/lib/typhoeus/request/callbacks.rb:128:in `map'
        from ~~/gems/typhoeus-0.6.9/lib/typhoeus/request/callbacks.rb:128:in `execute_callbacks'
        from ~~/gems/typhoeus-0.6.9/lib/typhoeus/request/operations.rb:35:in `finish'
        from ~~/gems/typhoeus-0.6.9/lib/typhoeus/easy_factory.rb:105:in `block in set_callback'
        from ~~/gems/ethon-0.7.1/lib/ethon/easy/response_callbacks.rb:65:in `call'
        from ~~/gems/ethon-0.7.1/lib/ethon/easy/response_callbacks.rb:65:in `block in complete'
        from ~~/gems/ethon-0.7.1/lib/ethon/easy/response_callbacks.rb:65:in `each'
        from ~~/gems/ethon-0.7.1/lib/ethon/easy/response_callbacks.rb:65:in `complete'
        from ~~/gems/ethon-0.7.1/lib/ethon/multi/operations.rb:148:in `check'
        from ~~/gems/ethon-0.7.1/lib/ethon/multi/operations.rb:161:in `run'
        from ~~/gems/ethon-0.7.1/lib/ethon/multi/operations.rb:43:in `perform'
        from ~~/gems/typhoeus-0.6.9/lib/typhoeus/hydra/runnable.rb:15:in `run'
        from ~~/gems/typhoeus-0.6.9/lib/typhoeus/hydra/memoizable.rb:51:in `run'
        from ~~/gems/manga-downloadr-1.0.1/lib/manga-downloadr.rb:124:in `fetch_images!'
        from ~~/gems/manga-downloadr-1.0.1/bin/manga-downloadr:55:in `<top (required)>'
        from ~~/gems/bin/manga-downloadr:23:in `load'
        from ~~/gems/bin/manga-downloadr:23:in `<main>'
        from ~~/gems/bin/ruby_executable_hooks:15:in `eval'
        from ~~/gems/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by barracuda156** [comment]
@akitaonrails What is the current status, does the gem work?
