### ISSUE TITLE
Can't run test mode

### ISSUE THREAD

**Issue by rosenfeld** [akitaonrails/manga-downloadr#6]
```
time bin/manga-downloadr --test                                                    
/home/rodrigo/temp/src/elixir-tests/manga-downloadr/lib/manga-downloadr/workflow.rb:30:in `fetch_chapters': wrong number of arguments (given 0, expected 1) (ArgumentError)                                                                                    
        from /home/rodrigo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/chainable_methods-0.1.3/lib/chainable_methods.rb:36:in `method_missing'                         
        from /home/rodrigo/temp/src/elixir-tests/manga-downloadr/lib/manga-downloadr/workflow.rb:23:in `run_tests'
        from bin/manga-downloadr:71:in `block in <main>'
        from /home/rodrigo/.rbenv/versions/2.3.1/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
        from bin/manga-downloadr:70:in `<main>'
```

**Comment by rosenfeld** [comment]
The problem seems to be the newer version of chainable_methods (0.1.3) which satisfies the Gemfile but is really backwards incompatible with 0.1.2 since it swaps the arguments passed to CM:

https://github.com/akitaonrails/manga-downloadr/blob/master/manga-downloadr.gemspec#L17

Swapping the arguments to CM allowed the app to work. I'm not submitting any patches as I have no ideas on how you prefer to fix this.

**Comment by akitaonrails** [comment]
Sorry about that, you're right, I fixed that.
